Revert "chore(deps): update dependency ansible to v11 (#506)"
This reverts commit 207d8f4dfafc3c173fe33af7b83ba3212e721fb3.

ERROR: No matching distribution found for ansible==11.0.0

Signed-off-by: Christian Berendt <berendt@osism.tech>